version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - echo "Installing pip dependencies..."
      - pip install --upgrade pip
      - pip install -r requirements.txt

  pre_build:
    commands:
      - echo "Running Django migrations..."
      - python manage.py migrate
    
  build:
    commands:
      - echo "Build phase - No build commands required for Django"

  post_build:
    commands:
      - echo "Build complete. Ready for deployment."

artifacts:
  files:
    - '**/*'
    
cache:
  paths:
    - ~/.cache/pip
